server {
  listen 80; 
    # in https use 443 and add ssl_certificate and ssl_certificate_key directives
  server_name _; 
  # match the hostname


  root /usr/share/nginx/html;
  # 	The folder to serve files from.
  index index.html;
  # 	When someone requests /, serve index.html.

  # SPA fallback — same role as Netlify's _redirects
  location / {
    try_files $uri $uri/ /index.html;
  }

#   When a request comes in for /dash/notes/123, nginx tries each of these in order until it finds one:

# $uri → "is there a file at /dash/notes/123?" → No.
# $uri/ → "is there a directory at /dash/notes/123/?" → No.
# /index.html → "fallback: serve index.html." → Yes! Brow

  # Cache static assets aggressively (1 year)
#   Why aggressive caching of /assets/
# Vite gives every JS/CSS file a content hash in its name: index-a1b2c3.js. When the file changes, the hash changes 
  location /assets/ {
    expires 1y;
    # catche for 1 year
    add_header Cache-Control "public, immutable";
    # Tell browsers "this file will never change at this URL" (true because Vite hashes filenames).
  }
}